# This file was generated by Nuitka and describes the types of the
# created shared library.

# At this time it lists only the imports made and can be used by the
# tools that bundle libraries, including Nuitka itself. For instance
# standalone mode usage of the created library will need it.

# In the future, this will also contain type information for values
# in the module, so IDEs will use this. Therfore please include it
# when you make software releases of the extension module that it
# describes.

import copy
import _version
import warnings
import numpy.distutils.misc_util
import types
import weakref
import lib
import fromnumeric
import ctypes
import threading
import urllib.request
import re
import nanfunctions
import numpy.compat.py3k
import mixins
import _thread
import memmap
import helper
import numpy.lib
import urllib2
import StringIO
import defmatrix
import _import_tools
import numpy.matrixlib.defmatrix
import py3k
import machar
import pydoc
import pickle
import textwrap
import dummy_thread
import numbers
import numpy
import numpy.core.records
import version
import fftpack
import inspect
import mmap
import utils
import umath
import numpy.linalg
import numpy.core.multiarray
import shape_base
import extras
import financial
import _globals
import numpy.version
import info
import pathlib
import chebyshev
import type_check
import copyreg
import einsumfunc
import linalg
import os
import numpy.lib.utils
import gzip
import functools
import _datasource
import numpy.core
import testing
import decimal
import imp
import index_tricks
import numpy.__config__
import numpy.ma.mrecords
import shutil
import abc
import numpy.core.numeric
import bz2
import operator
import numpy.core._internal
import matrixlib
import function_base
import sys
import numpy.core.umath
import hermite_e
import lzma
import arraypad
import core
import thread
import mtrand
import compat
import tempfile
import tokenize
import numeric
import numpy.lib.function_base
import struct
import arraysetops
import itertools
import _internal
import stride_tricks
import urlparse
import getlimits
import numerictypes
import urllib.parse
import numpy.testing
import ufunclike
import npyio
import laguerre
import cPickle
import arrayprint
import io
import zipfile
import hermite
import multiarray
import glob
import numpy.core.fromnumeric
import _iotools
import ast
import locale
import numpy.lib.twodim_base
import numpy.lib.stride_tricks
import arrayterator
import numpy.core.numerictypes
import records
import future_builtins
import numpy.ma
import collections
import numpy.compat
import importlib.machinery
import polynomial
import _polybase
import os.path
import twodim_base
import copy_reg
import legendre
import urllib.error
import builtins
import numpy.lib.index_tricks
import math
import numpy.matrixlib
import numpy.lib.type_check
import defchararray
import numpy.fft
import _inspect
import numpy.dual
import __builtin__

# This is not Python source even if it looks so. Make it clear for
# now. This was decided by PEP 484 designers.
__name__ = ...

